site_name: Projekt
nav:
  - Strona główna: index.md
  - Teoria: teoria.md
  - Temat projektu: tematprojektu.md
  - Przykłady: przyklady.md
  - Praktyka: praktyka.md
  - Autorzy: autorzy.md
theme: readthedocs