site_name: Jak dbać o rośliny doniczkowe?
nav:
  - Strona główna: index.md
  - Temat projektu: tematprojektu.md
  - Teoria: teoria.md
  - Przykłady: przyklady.md
  - Wydarzenia: praktyka.md
  - Autorzy: autorzy.md
theme: readthedocs