site_name: Jak dbać o rośliny doniczkowe?
nav:
  - Strona główna: index.md
  - Temat projektu: tematprojektu.md
  - Teoria: teoria.md
  - Przykłady: przyklady.md
  - Wydarzenia: wydarzenie.md
  - Autorzy: autorzy.md
  
theme:
  name: material
  font:
    text: Nunito
  palette: 
    primary: green
    accent: teal
  features:
    navigation.tabs.sticky
    navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - header.autohide
  logo: img/logo.png
plugins:
  - search:
      suggest: true